#pragma config(Sensor, dgtl1,  sonar,          sensorSONAR_inch)
#pragma config(Motor,  port1,           motory,         tmotorVex393_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{

while (0==0) {


if (SensorValue[dgtl1] != -1) {
	if (SensorValue[dgtl1] < 10) {

		motor[motory] = -127;

	}


}
else {
	motor[motory] = 0;

}






}


}
