#pragma config(Motor,  port1,           wheelRearLeft, tmotorVex393_HBridge, openLoop, reversed)
#pragma config(Motor,  port2,           wheelFrontRight, tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port3,           mobileGoalLift, tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           wheelRearRight, tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port5,           liftLeftSide,  tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port6,           liftRightSide, tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           coneFlipLeft,  tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           coneFlipRight, tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           coneClaw,      tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port10,          wheelFrontLeft, tmotorVex393_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#pragma platform(VEX)

//Competition Control and Duration Settings// DON'T MODIFY!
#pragma competitionControl(Competition)
#pragma autonomousDuration(20)
#pragma userControlDuration(120)

#include "Vex_Competition_Includes.c"   //Main competition background code...do not modify!




/////////////////////////////////////////////////////////////////////////////////////////
//
//                          Pre-Autonomous Functions
//
// You may want to perform some actions before the competition starts. Do them in the
// following function.
//
/////////////////////////////////////////////////////////////////////////////////////////
void pre_auton() {
  // Set bStopTasksBetweenModes to false if you want to keep user created tasks running between
  // Autonomous and Tele-Op modes. You will need to manage all user created tasks if set to false.
					bStopTasksBetweenModes = true;

	// All activities that occur before the competition starts
	// Example: setting servo positions, extending arm, loading shotgun ...
    // If your robot is a Transformer(copyrighted), then transformation occurs here

}





/////////////////////////////////////////////////////////////////////////////////////////
//
//                             Used Variables and Funcions
//
// Any variables or functions that you will be using are initialized in this area right here.
//
/////////////////////////////////////////////////////////////////////////////////////////

int vectorFrontLeft = 0;
int vectorFrontRight = 0;
int vectorRearLeft = 0;
int vectorRearRight = 0;

void resetWheelVectors() {
	vectorFrontLeft = 0;
	vectorFrontRight = 0;
	vectorRearLeft = 0;
	vectorRearRight = 0;
}

void runWheels() {
	motor[wheelFrontLeft] = vectorFrontLeft;
	motor[wheelFrontRight] = vectorFrontRight;
	motor[wheelRearLeft] = vectorRearLeft;
	motor[wheelRearRight] = vectorRearRight;
}




/////////////////////////////////////////////////////////////////////////////////////////
//
//                                 Autonomous Task
//
// This task is used to control your robot during the autonomous phase of a VEX Competition.
// You must modify the code to add your own robot specific commands here.
//
/////////////////////////////////////////////////////////////////////////////////////////
task autonomous() {

	// rip

}




/////////////////////////////////////////////////////////////////////////////////////////
//
//                                 User Control Task
//
// This task is used to control your robot during the user control phase of a VEX Competition.
// You must modify the code to add your own robot specific commands here.
//
/////////////////////////////////////////////////////////////////////////////////////////
task usercontrol() {
/* an infinite loop */
while (0 == 0) // lol it looks like a face
{

	resetWheelVectors();

	vectorFrontLeft += vexRT[Ch3];
	vectorFrontRight += vexRT[Ch3];
	vectorRearLeft += vexRT[Ch3];
	vectorRearRight += vexRT[Ch3];

	vectorFrontLeft += vexRT[Ch1];
	vectorFrontRight -= vexRT[Ch1];
	vectorRearLeft += vexRT[Ch1];
	vectorRearRight -= vexRT[Ch1];

	runWheels();

	if (vexRT[Btn7U] == 1) {
		motor[liftLeftSide] = 127;
		motor[liftRightSide] = 127;
	} else {
		motor[liftLeftSide] = 0;
		motor[liftRightSide] = 0;
	}

	if (vexRT[Btn5U] == 1) {
		motor[coneFlipLeft] = 127;
		motor[coneFlipRight] = 127;
	} else if (vexRT[Btn5D] == 1) {
		motor[coneFlipLeft] = -127;
		motor[coneFlipRight] = -127;
	} else {
		motor[coneFlipLeft] = 0;
		motor[coneFlipRight] = 0;
	}

	if (vexRT[Btn8U] == 1) {
		motor[mobileGoalLift] = 127;
	} else if (vexRT[Btn8D] == 1) {
		motor[mobileGoalLift] = -127;
	} else {
		motor[mobileGoalLift] = 0;
	}

	if (vexRT[Btn6U] == 1) {
		motor[coneClaw] = 20;
	} else if (vexRT[Btn6D] == 1) {
		motor[coneClaw] = -60;
	} else {
		motor[coneClaw] = 0;
	}

}
}
