#pragma config(Motor,  port2,           leftdrive,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           frontbelt,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           guidewheels,   tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           backbelt,      tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port6,           launcher1,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           launcher2,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           rightdrive,    tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#pragma platform(VEX)

//Competition Control and Duration Settings
#pragma competitionControl(Competition)
#pragma autonomousDuration(15)
#pragma userControlDuration(105)

#include "Vex_Competition_Includes.c"   //Main competition background code...do not modify!

/////////////////////////////////////////////////////////////////////////////////////////
//
//                          Pre-Autonomous Functions
//
// You may want to perform some actions before the competition starts. Do them in the
// following function.
//
/////////////////////////////////////////////////////////////////////////////////////////

void pre_auton()
{

}

/////////////////////////////////////////////////////////////////////////////////////////
//
//                                 Autonomous Task
//
// This task is used to control your robot during the autonomous phase of a VEX Competition.
// You must modify the code to add your own robot specific commands here.
//
/////////////////////////////////////////////////////////////////////////////////////////

task autonomous()
// assuming port1 is left drive motor and port 2 is right drive motor. need to program left motor
// at a slower speed than right motor so robot moves in a straight line rather than curving to the right
{
  motor[port9] = 65;/////////////////////////////////////////////////////////////////////////////////
  motor[port2] = 70;///////                                                                        //
  motor[port3] = 70;
  motor[port4] = 90;
  motor[port5] = 70;
  wait1Msec(1500);////////// this section is moving robot from starting tile to spot close to goal  //
  motor[port3] = 0;
  motor[port5] = 0;                                                                    //
  wait1Msec(5500);
  motor[port2] = 0;
  motor[port9] = 0;
  motor[port4] = 0;       ///////////////////////////////////////////////////////////////////////////////
  //assuming port3 is backbelt, port4 is front belt, port5 is guide wheels, and port6 and port8 are launcher motors
  motor[port4] = 127;
  motor[port3] = 45;/////////////////////////////////////////////////////////////////////////////////////////////////
  motor[port5] = 45;/////////                                                                                      //
  motor[port6] = 127;////////                                                                                      //
  motor[port7] = 127;////////                                                                                      //
  wait1Msec(5000);/////////// this section starts the guide wheels, belts, and launcher to shoot balls into goal   //
  motor[port3] = 0;
  motor[port4] = 0;//////////                                                                                      //
  motor[port5] = 0;//////////                                                                                      //
  motor[port6] = 0;//////////                                                                                      //
  motor[port7] = 0;//////////////////////////////////////////////////////////////////////////////////////////////////
}

/////////////////////////////////////////////////////////////////////////////////////////
//
//                                 User Control Task
//
// This task is used to control your robot during the user control phase of a VEX Competition.
// You must modify the code to add your own robot specific commands here.
//
/////////////////////////////////////////////////////////////////////////////////////////

task usercontrol()
{

	while (1 == 1)
	{
		motor[port9] = vexRT[Ch2] / 2;
		motor[port2] = vexRT[Ch3] / 2;

	  if(vexRT[Btn5U] == 1)
	  {
		  motor[port6] = 127;
	  }
	  else
	  {
		  motor[port6] = 0;
	  }
	  if(vexRT[Btn6U] == 1)
	  {
		  motor[port7] = 127;
	  }
	  else
	  {
		  motor[port7] = 0;
	  }
	  if(vexRT[Btn7DXmtr2] == 1)
	  {
		  motor[port4] = -127;
	  }
	  else
	  {
		  motor[port4] = 0;
	  }
	  if(vexRT[Btn5UXmtr2] == 1)
	  {
		  motor[port3] = 45;
	  }
	  else
	  {
		  motor[port3] = 0;
	  }
	  if(vexRT[Btn6UXmtr2] == 1)
	  {
		  motor[port5] = 45;
	  }
	  else
	  {
		  motor[port5] = 0;
	  }
  }
}
